### ISSUE TITLE
Sensor State - Nighttime

### ISSUE THREAD

**Issue by Scags104** [alexander0042/pirate-weather-hacs#2]
Seems like the icons are correct at night but the sensor state is not. 

Example: Last night was a clear night, so there was just a moon icon but the sensor state read "Sunny" through the entirety of the night. 

Maybe even just replacing this with "Clear" beyond sunset is probably more accurate?

Thank you

**Comment by 1darklyte** [comment]
Also had this happen last night :)

**Comment by alexander0042** [comment]
Had to wait until after sunset to fix this one, but I *think* I've got it. It was a glitch where the "current" conditions would never return night unless it was partly cloudy. Basically, a rogue if statement.  

I'm going to wait a couple days to close this one, just to make sure the sensor is behaving as expected, but it seems to be working with just this API back-end change

**Comment by 1darklyte** [comment]
This is what I see at the moment and its 10:55pm EST here : https://prnt.sc/135cmb7

:)

**Comment by Scags104** [comment]
Confirmed for me as well, thanks again!

**Comment by alexander0042** [comment]
Perfect! I'm going to close this issue for now then, since this particular bug seems to have been squashed!
